### ISSUE TITLE
Why to adjust for high latitudes if times determination is already possible?

### ISSUE THREAD

**Issue by maherahmed** [islamic-network/prayer-times#9]
AlsalamuAlykom,

https://github.com/islamic-network/prayer-times/blob/8e1bff8ae049dc1dca31a4c02ba5cc8204e1aa88/src/PrayerTimes/PrayerTimes.php#L460

Here it applies the high latitude adjustment if for example the time between Fajr and sunrise is greater than the night portion, should not the high latitude adjustment only applied if the times determination according to the calculation method respective angles is not possible?

**Comment by meezaan** [comment]
This line was also committed 8 years ago, but I believe this was done because without the adjustment a NaN value was produced for the time. I don't remember why, exactly (I'd have to follow the whole calculation through now to get there), but yes, the calculation was not possible, and if I recall correctly, the problem existed in the original library too.

**Comment by meezaan** [comment]
Resolved with https://github.com/islamic-network/api.aladhan.com/issues/76.
